# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7cc07a00-e340-460c-82ec-52afacbe72ba";
      fsType = "ext4";
    };

  fileSystems."/mmc" =
    { device = "/dev/disk/by-uuid/7C5B-9051";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/70b04ad7-ee43-4502-937b-16da8b59df32"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
