# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # SSD optimization?
  #boot.kernel.sysctl {
  #  "vm.swappiness" = 90;
  #};

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/40238ada-6f09-40ea-87b8-c076082c1234";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9D18-7EA3";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.intel.updateMicrocode = true;
  #hardware.cpu.amd.updateMicrocode = true;

  hardware.bluetooth.enable = false;

  # Enable sound.
  sound.enable = true;
  #sound.mediaKeys.enable
  hardware.pulseaudio.enable = true;
  #hardware.pulseaudio.package = pulse;

  nixpkgs.config = {
    allowUnfree = true;
  };

  services.xserver = {
    videoDrivers = ["nvidia"];
  };
}
